# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dueño', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha de la visita')),
                ('entrada', models.TextField()),
                ('peso', models.FloatField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='fichas.Animal')),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='ModelWithImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha de vacunacion')),
                ('nombre', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='fichas.Animal')),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('modelwithimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fichas.ModelWithImage')),
            ],
            bases=('fichas.modelwithimage',),
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('modelwithimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fichas.ModelWithImage')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Especie')),
            ],
            bases=('fichas.modelwithimage',),
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Especie'),
        ),
        migrations.AddField(
            model_name='animal',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Raza'),
        ),
    ]
