# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaVacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de la visita'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de vacunacion'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='vacuna',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fichas.MetaVacuna'),
        ),
    ]
