# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_auto_20161009_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'animales'},
        ),
        migrations.AlterModelOptions(
            name='metavacuna',
            options={'verbose_name': 'vacuna', 'verbose_name_plural': 'vacunas'},
        ),
    ]
